new_players:
  header: "New Players"
  subheader: "Find Out Your Birth Card"
  instructions: "Enter your Date of Birth:"
  button: "Go"
returning_players:
  header: "Returning Players"
  subheader: "Login to get back in the game:"
  instructions: "A temporary password was emailed to you."
  button: "Get Back In The Game"
  email_name: "Profile Email"
  password_name: "Password"
  remember_name: "Remember me"
  reset_name: "Reset Password"
new_teammates:
  subheader: "Look Up Someone Else's Cards"
  instructions: "Enter their Date of Birth"

card_previews:
  member:
    personality:
      header: "Your Personality Card"
      description: |
        Your Personality Card is the second most important card in your life. You may even be more identified with it than your Birth Card. It’s how you show up in your world. 

        <strong class='joining_players_club'>Join the Players Club</strong> to find out your Personality Card.  It's FREE to join.
      cusp_picker: "Your birthday is on an astrological cusp. To correctly determine your Personality Card, we need to know which is your Western Astrological sign. If you know it, please click it here:"
      cusp_unsure: "If you are unsure of your Astrological Birth Sign, you may"
      email: "dinklage@thrones.net"
      cusp_unsure_two: "with the time and place of your birth, and we will look it up for you. We will respond to your email in about 24 hours. Alternately, there are free lookup tools on the web for you to look up your Astrological sign. And, if you want, you can play with each Astrological Sign option to see which Personality Card appears. A button will link you back to this page to change your choice again."
      button: "Jump Over the Cusp"
    yearly:
      header_last: "Last Yearly Card"
      header: "Your Yearly Card"
      header_next: "Next Yearly Card"
      subheader: "This card represents the main theme of your year. Your year starts from your last birthday until your next birthday."
      description: |
         Starting on our Birthday, we have new cards to play each year. Based on which cards are in play, we have specific challenges to resolve and specific opportunities for growth. 

         <strong class='joining_players_club'>Join the Players Club</strong> to find out the card that indicates the central theme of your life this year.  It's FREE to join.
      button_last: "See Last Year's Card"
      button_current: "See This Year's Card"
      button_next: "See Next Year's Card"
    planetary:
      header_last: "Previous 52-Day Card"
      header: "Your 52-Day Card"
      header_next: "Next 52-Day Card"
      subheader: "This card represents the current period of your year. It indicates a specific energy pattern in play for this 52-day cycle."
      description: |
          During our year, from Birthday to Birthday, we move through seven specific cycles of influence. Each cycle in the year is 52 days long. 

          <strong class='joining_players_club'>Join the Players Club</strong> to find out which card is in play for you right now during this cycle, so you can clarify what’s happening for you right now.  It's FREE to join.
      button_last: "See Your Previous Card"
      button_current: "See Your Current Card"
      button_next: "See Your Next Card"
  guest:
    personality:
      header: "Their Personality Card"
      description: |
        The Personality Card is the second most important card in their life. They may even be more identified with it than the Birth Card. It’s how they show up in their world. 

        <strong class='joining_players_club'>Join the Players Club</strong> to find out your Personality Card.  It's FREE to join.
      cusp_picker: "This birthday is on an astrological cusp. To correctly determine the Personality Card, we need to know which is their Western Astrological sign. If you know it, please click it here:"
      cusp_unsure: "If you are unsure of their Astrological Birth Sign, you may"
      cusp_unsure_two: "with the time and place of your birth, and we will look it up for you. We will respond to your email in about 24 hours. Alternately, there are free lookup tools on the web for you to look up an Astrological sign. And, if you want, you can play with each Astrological Sign option to see which Personality Card appears. A button will link you back to this page to change your choice again."
      button: "Jump Over the Cusp"
    yearly:
      header_last: "Last Yearly Card"
      header: "Their Yearly Card"
      header_next: "Next Yearly Card"
      subheader: "This card represents the main theme of the year. Your year is from your last birthday until your next birthday."
      description: |
         Starting on our Birthday, we have new cards to play each year. Based on which cards are in play, we have specific challenges to resolve and specific opportunities for growth. 

         <strong class='joining_players_club'>Join the Players Club</strong> to find out the card that indicates the central theme of your life this year.  It's FREE to join.
      button_last: "See Last Year's Card"
      button_current: "See This Year's Card"
      button_next: "See Next Year's Card"
    planetary:
      header_last: "Previous 52-Day Card"
      header: "Their 52-Day Card"
      header_next: "Next 52-Day Card"
      subheader: "This card represents the current period of their year. It indicates a specific energy pattern in play for this 52-day cycle."
      description: |
          During our year, from Birthday to Birthday, we move through seven specific cycles of influence. Each cycle in the year is 52 days long. 

          <strong class='joining_players_club'>Join the Players Club</strong> to find out which card is in play for you right now during this cycle, so you can clarify what’s happening for you right now.  It's FREE to join.
      button_last: "See Their Previous Card"
      button_current: "See Their Current Card"
      button_next: "See Their Next Card"
      

member_form:
  header: "Join The Players Club for FREE"
  subheader: "It's FREE"
  description: |
    Look up your cards to play. And look up other people's cards too!

    Create your FREE Player Profile.

    - You'll receive a temporary password and other important information emailed to you. So please make sure to provide a valid email you check regularly. 

  privacy_policy: |
    <span class='terms'>Your email address is safe with us. We will never share it with anyone. And you may always opt out of emails or unsubscribe at a later date if you wish.</span>
    