member_form:
  header: "Join The Players Club for FREE"
  subheader: "It's FREE"
  description: |
    Look up your cards to play! Discover your Personality Card, your Yearly Card, and your 52-Day Card. And look up other people's cards too!

    Create your FREE Player Profile. 
    
    Please be sure you've entered your own Birth Date when you set your profile. If you need to change the Birth Date, please click the orange Birth Card Lookup button above.

    - You'll receive a temporary password and other important information emailed to you. So please make sure to provide a valid email you check regularly. 

  instructions: "Create Your FREE Player Profile"
  privacy_policy: |
    Policy for Free Members: Your email address is safe with us. We will never share it with anyone. And you may always unsubscribe at any time.

password:
  incorrect: |
    Oops, it looks like you're entering the wrong password.<br>
    The temporary password is 'ENV['INITIAL_PASSWORD']'.<br>
    You can also reset your password via the link below.

subscription:
  teaser:
    header: Win Win
    subheader: Invest in your personal growth and support our mission to elevate humanity with this game-changing Knowledge.
    offer: |
      For $ENV['MONTHLY_PRICE'] per month, you'll discover

      * Your personal Daily Card. This is a biggie. Knowing the meaning of this Card aligns your life for success each and every day!
      * Your upcoming Yearly Card, so you can see what's coming and your previous Yearly Card, so you can review your life lessons.
      * Your upcoming 52-Day Card, so you can plan accordingly and your previous 52-Day Card, so you can process what just happened in your life.
      * The meaning of the Planetary influence of your 52-Day Cycle, so you have greater awareness to play your cards right.
      * AND we'll send you a series of Training Videos with Alexander that will unlock key aspects of this Knowledge for you.
      * PLUS, your contribution supports us to further our mission of sharing this game-changing Knowledge!
      * All for less than the price of a cup of coffee.

      It all starts with a Free 7-day trial so you can check it out at no risk to you. Cancel at any time.
      
    accept: Yes, begin my FREE 7-day trial.
    defer: No, this is enough for now.
  checkout:
    submit: Yes, I'm ready to learn more!
  transaction:
    succeeded: "Thank you for your subscription and your support. Please REFRESH your browser page to view all the features of your Premium Membership. And may you play your cards right, so that you master the game of your life."
    failed: Your transaction was not completed.  This may be due to bank security measures, which are very tight these days.  If you use a different payment method or contact your bank, perhaps the next attempt will succeed.
    past_due: "Uh Oh! There was a problem with your Players Club subscription!"
    unresolved: "Your payment is unresolved."
    late: "A chance to update your payment method.."
    over: "Your access is curtailed."
  upgrade:
    succeeded: "Wonderful choice.  Join us in the Salon at ENV['PLAYERS_CLUB_SALON_URL'] .  The address has been emailed to you."
  update:
    initiate: "I would like to update my payment method."
    accept: "Do you need to update your payment information?"
    submit: "Update my payment."
    succeeded: "Thank you."
    failed: "That payment method was not finalized."
  unsubscribe:
    link: I am ready to end my subscription.
    confirm: Are you sure you wish to end your subscription?
  cancellation:
    policy: "Policy for Premium Users: Once you enter your Credit Card information, you begin a 7-day introductory free trial of your Premium Membership. After the trial period, you will be billed $ENV['MONTHLY_PRICE'] automatically each month. We keep all your information strictly private. We do not share your information with any third parties. You may cancel your subscription at any time, including during the 7-day introductory free Premium trial."

book:
  question: "Want to learn more?"
  answer: "Get the book."

coaching:
  question: Want to learn more?
  answer: Ask Alexander

new_players:
  header: "Birth Card Lookup"
  subheader: |
    Simply enter a Birth Date. Afterwards, you can join to look up Yearly Cards too! 
  instructions: 
  button: "Go"
returning_players:
  header: "Returning Players"
  subheader: "The Players Clubs Has Moved To The Source Cards"
  instructions: "A temporary password was emailed to you."
  password_hint: "The temporary password is 'ENV['INITIAL_PASSWORD']'"
  button: "Get Back In The Game"
  email_name: "Profile Email"
  password_name: "Password"
  remember_name: "Check This Box To Stay Logged In"
  reset_name: "Reset Password"
new_teammates:
  subheader: "Look Up Someone Else's Cards"
  instructions: "Enter their Date of Birth"

navigation:
  lookup: 'Birth Card Lookup'
  reading: 'My Reading'
  log_out: 'Log Out'
  upgrade: 'Upgrade My Membership'

preserving:
  add: 'Save Date'
  dub: 'Add Name'
  alter: 'Edit'
  remove: 'Remove'

exit_interview:
  instructions: |
    Because we're committed to helping you elevate your life and because we want to elevate our own game, please take a moment to help us understand why this service did not satisfy you.

    Please check ALL the reasons that apply.
  
  unused: "I just don't use it."
  elsewhere: "I can find this same information elsewhere."
  cumbersome: "It's too cumbersome to login each time."
  expense: "I'm trying to reduce my monthly expenses."
  accuracy: "The information about my cards is just not accurate."
  specific: "The information here is not detailed enough."
  applicable: "I don't know how to use this information and apply it in my life."
  thoughts: "Other. Please let us know how we can improve this service."
  signoff: "Thank you for helping us to elevate our game."
  
  review_title: "Thank you. We appreciate your feedback."
  review_thanks: "And we're wondering... Did you you watch the free Training Videos?"
  review_videos: "These videos (that were emailed to you) explain how to best utilize this toolkit to start activating magical experiences in your life.  And sometimes it does take time to get used to working with these cards as a magical toolkit."
  review_invitation: "Would you like to give this Players Club another try for this month?"
  remain: "Yes, Ok, on second thought, I'll give it another try."
  leave: "Thanks, but I'm ready to end my subscription now."
  confirm: "This will end your subscription to the Players Club."

heading:
  member:
    birth:
      header: "Birth Card"
    personality:
      header: "Personality Card"
      subheader: 
    yearly:
      header_last: "Last Yearly Card"
      header: "Your Yearly Card"
      header_next: "Coming Yearly Card"
      subheader: "This card represents the main theme of your year. Your year starts from your last birthday until your next birthday."
    planetary:
      header_last: "Previous 52-Day Card"
      header: "Your 52-Day Card"
      header_next: "Coming 52-Day Card"
      subheader: "This card represents a specific energy pattern in play for this 52-day cycle, "
    daily:
      header: "Today's Card"
      subheader: "This card will be with you until midnight."
    tomorrow:
      header: "Tomorrow's Card"
      subheader: "This card will join you at midnight."
    yesterday:
      header: "Yesterday's Card"
      subheader: "This card was with you yesterday."
    cinderella:
      header: "Today's Card"
      subheader: "This card has been with you since midnight."
  acquaintance:
    birth:
      header: "Their Birth Card"
    personality:
      header: "Their Personality Card"
      subheader: 
    yearly:
      header_last: "Last Yearly Card"
      header: "Their Yearly Card"
      header_next: "Coming Yearly Card"
      subheader: "This card represents the main theme of the year. Your year is from your last birthday until your next birthday."
    planetary:
      header_last: "Previous 52-Day Card"
      header: "Their 52-Day Card"
      header_next: "Coming 52-Day Card"
      subheader: "This card represents the current period of their year. It indicates a specific energy pattern in play for this 52-day cycle."

button:
  member:
    birth:
      button_current: "See Your Birth Card"
    personality:
      button: "Jump Over the Cusp"
    yearly:
      button_last: "See Last Year's Card"
      button_current: "See This Year's Card"
      button_next: "See Next Year's Card"
    planetary:
      button_last: "See Your Previous Card"
      button_current: "See Your Current Card"
      button_next: "See Your Next Card"
    daily:
      button_current: "See Your Personal Daily Card"
  acquaintance:
    personality:
      button: "Jump Over the Cusp"
    yearly:
      button_last: See Last Year's Card
      button_current: "See This Year's Card"
    planetary:
      button_last: "See Their Previous Card"
      button_current: "See Their Current Card"

preview:
  personality:
    description: |
      Your Personality Card is the second most important card in your life. You may even be more identified with it than your Birth Card. It’s how you show up in your world. 

      <strong class='joining_players_club'>Join the Players Club</strong> to find out your Personality Card.  It's FREE to join.
  yearly:
    description: |
      Starting on our Birthday, we have new cards to play each year. Based on which cards are in play, we have specific challenges to resolve and specific opportunities for growth. 

      <strong class='joining_players_club'>Join the Players Club</strong> to find out the card that indicates the central theme of your life this year.  It's FREE to join.
  planetary:
    description: |
      During our year, from Birthday to Birthday, we move through seven specific cycles of influence. Each cycle in the year is 52 days long. 

      <strong class='joining_players_club'>Join the Players Club</strong> to find out which card is in play for you right now during this cycle, so you can clarify what’s happening for you right now.  It's FREE to join.
      
cusp:
  member:
    personality:
      cusp_picker: "Your birthday is on an astrological cusp. To correctly determine your Personality Card, we need to know which is your Western Astrological sign. If you know it, please click it here:"
      cusp_unsure: "If you are unsure of your Astrological Birth Sign, you may"
      cusp_unsure_two: "with the time and place of your birth, and we will look it up for you. We will respond to your email in about 24 hours. Alternately, there are free lookup tools on the web for you to look up your Astrological sign. And, if you want, you can play with each Astrological Sign option to see which Personality Card appears. A button will link you back to this page to change your choice again."
      
  acquaintance:
    personality:
      cusp_picker: "This birthday is on an astrological cusp. To correctly determine the Personality Card, we need to know which is their Western Astrological sign. If you know it, please click it here:"
      cusp_unsure: "If you are unsure of their Astrological Birth Sign, you may"
      cusp_unsure_two: "with the time and place of their birth, and we will look it up for you. We will respond to your email in about 24 hours. Alternately, there are free lookup tools on the web for you to look up an Astrological sign. And, if you want, you can play with each Astrological Sign option to see which Personality Card appears. A button will link you back to this page to change your choice again."
