new_players:
  header: "New Players"
  subheader: "Find Out Your Birth Card"
  instructions: "Enter your Date of Birth:"
  button: "Go"
returning_players:
  header: "Returning Players"
  subheader: "Login to get back in the game:"
  instructions: "A temporary password was emailed to you."
  button: "Get Back In The Game"
  email_name: "Profile Email"
  password_name: "Password"
  remember_name: "Remember me"
  reset_name: "Reset Password"

card_previews:
  personality:
    header: "Personality Card"
    description: |
      Your Personality Card is the second most important card in your life. You may even be more identified with it than your Birth Card. It’s how you show up in your world. 
      
      <strong class='joining_players_club'>Join the Players Club</strong> to find out your Personality Card.  It's FREE to join.
    button: "Jump Over the Cusp"
  yearly:
    header_last: "Last Yearly Card"
    header_current: "This Yearly Card"
    header_next: "Next Yearly Card"
    subheader: "This card represents the main theme of your year. Your year starts from your last birthday until your next birthday."
    description: |
       Starting on our Birthday, we have new cards to play each year. Based on which cards are in play, we have specific challenges to resolve and specific opportunities for growth. 
       
       <strong class='joining_players_club'>Join the Players Club</strong> to find out the card that indicates the central theme of your life this year.  It's FREE to join.
    button_last: "See Last Year's Card"
    button_current: "See This Year's Card"
    button_next: "See Next Year's Card"
  planetary:
    header_last: "Previous 52-Day Card"
    header_current: "This 52-Day Card"
    header_next: "Next 52-Day Card"
    subheader: "This card represents the current period of your year. It indicates a specific energy pattern in play for this 52-day cycle."
    description: |
        During our year, from Birthday to Birthday, we move through seven specific cycles of influence. Each cycle in the year is 52 days long. 
        
        <strong class='joining_players_club'>Join the Players Club</strong> to find out which card is in play for you right now during this cycle, so you can clarify what’s happening for you right now.  It's FREE to join.
    button_last: "See Previous Card"
    button_current: "See Current Card"
    button_next: "See Next Card"

member_form:
  header: "Join The Players Club for FREE"
  subheader: "It's FREE"
  description: |
    Look up your cards to play. And look up other people's cards too!

    Create your FREE Player Profile.

    - Note: You will receive a temporary password and other important player information sent to the email you provide. So please provide a valid email that you check regularly. 

  privacy_policy: |
    <span class='terms'>Your email address is safe with us. We will never share it with anyone. And you may always opt out of emails or unsubscribe at a later date if you wish.</span>

replace_card:
  button: "Jump Over the Cusp"
  
show:
  personality_card:
    cusp_picker: "This birthday is on an astrological cusp. To correctly determine this Personality Card, we need to know which is the Western Astrological sign. If you know it, please click it here:"
    cusp_unsure: "If you are unsure of the Astrological Birth Sign, you may"
    email: "dinklage@thrones.net"
    cusp_unsure_two: "with the time and place of birth, and we will look it up for you. We will respond to your email in about 24 hours. Alternately, there are free lookup tools on the web for you to look up the Astrological sign. And, if you want, you can play with each Astrological Sign option to see which Personality Card appears. A button will link you back to this page to change your choice again."