new_players:
  header: "Choose Your Birthday"
  header1: "Three Card Reading"
  header2: " Source Card Reading"
  instructions: |
    Then Click Enter
  button: "Enter"
  invitation: "Click on each card to read the game of your life."

card_reading:
  birth_card:
    identification: "Your Birth Card is the"
    symbolizing: "This pattern symbolizes the primary recurring experience of your life."
    instructions: "Click the Card to learn more."
  personality_card:
    identification: "Your Personality Card is the"
    symbolizing: "This ruling pattern symbolizes the identity that may define you."
    instructions: "Click the Card to learn more."
    cusp: "Your birthday is on an astrological cusp. If you know your sign, click it below. If you're unsure, flip the next card and check both options from your Birthday page."
  birthday_card:
    identification: "For the birthday of"
    instructions: "To learn more about the patterns of your birthday and to get inspiration for your life, click above on your Birthday Card."

navigation:
  another_lookup: "Look Up Another Birthday"
